apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mw7ee8de4-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/mw7ee8de4-dotnet-basic